title: learn-typescript
tagline: A brand new course on Learning Lab
description: Learn TypeScript
template:
  repo: learn-typescript-template
  name: learn-typescript
before:
  - type: createIssue
    title: Welcome to the first Issue!
    body: new-issue.md
steps:
  - title: Install GitHub
    description: Learn How to Install GitHub
    event: issues.closed
    link: '{{ repoUrl }}'
    actions:
      - type: createIssue
        title: Super Super Geil!
        body: new-issue.md
  - title: Install NodeJS
    description: Learn How to Install NodeJS
    event: issues.closed
    link: '{{ repoUrl }}'
    actions:
      - type: createIssue
        title: Super Super Geil - Part 2
        body: new-issue.md

